// src/lib/mock-posts.ts
// Posts de ejemplo para desarrollo/emergencia

export const mockPosts = [
  {
    title: "GTA 6 confirma Vice City como escenario principal",
    slug: "gta-6-vice-city-confirmado",
    description: "Rockstar Games ha confirmado oficialmente que GTA 6 tendrá lugar en una versión moderna de Vice City con gráficos de última generación.",
    date: "2026-02-27T18:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-6",
    type: "noticias",
  },
  {
    title: "Nuevo DLC de GTA Online: Vice City Stories",
    slug: "gta-online-dlc-vice-city",
    description: "El esperado DLC que conecta GTA Online con el universo de GTA 6 ya tiene fecha de lanzamiento confirmada para marzo de 2026.",
    date: "2026-02-26T15:30:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-online",
    type: "noticias",
  },
  {
    title: "Guía completa: Todos los coleccionables de GTA 5",
    slug: "guia-coleccionables-gta-5",
    description: "Encuentra todas las piezas de nave espacial, letras ocultas y tesoros sumergidos con nuestra guía paso a paso ilustrada.",
    date: "2026-02-25T10:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-5",
    type: "guias",
  },
  {
    title: "Rockstar anuncia nuevo parche anti-trampas",
    slug: "rockstar-parche-anti-trampas",
    description: "La última actualización de GTA Online incluye mejoras significativas en el sistema anti-trampas y nuevas penalizaciones.",
    date: "2026-02-24T12:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-online",
    type: "noticias",
  },
  {
    title: "Análisis: Los mejores coches de GTA Online 2026",
    slug: "mejores-coches-gta-online-2026",
    description: "Repasamos los vehículos más rápidos, potentes y populares de GTA Online en la actualidad con estadísticas detalladas.",
    date: "2026-02-23T09:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-online",
    type: "analisis",
  },
  {
    title: "GTA San Andreas Definitive Edition recibe actualización",
    slug: "gta-san-andreas-actualizacion",
    description: "Rockstar lanza un parche que corrige los principales bugs reportados por la comunidad en la versión remasterizada.",
    date: "2026-02-22T14:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-san-andreas",
    type: "noticias",
  },
  {
    title: "Trucos secretos de GTA Vice City que no conocías",
    slug: "trucos-secretos-gta-vice-city",
    description: "Descubre códigos ocultos y easter eggs que Rockstar nunca documentó oficialmente en el clásico de 2002.",
    date: "2026-02-21T11:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-vice-city",
    type: "guias",
  },
  {
    title: "Comparativa gráfica: GTA 5 vs GTA 6",
    slug: "comparativa-grafica-gta-5-gta-6",
    description: "Analizamos las diferencias técnicas entre ambos juegos basándonos en los tráilers oficiales y capturas filtradas.",
    date: "2026-02-20T16:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-6",
    type: "analisis",
  },
  {
    title: "Los mejores mods de GTA 4 para 2026",
    slug: "mejores-mods-gta-4-2026",
    description: "Selección de los mods más impresionantes que transforman completamente la experiencia de Liberty City.",
    date: "2026-02-19T13:00:00Z",
    cover: "/images/default-cover.jpg",
    game: "gta-4",
    type: "guias",
  },
];